# Hoofd playbook voor (router)
- name: Hoofd-playbook voor alle laptops
  hosts: localhost
  connection: local
  gather_facts: false

  pre_tasks:
    # 1. Lees het /etc/laptop-group bestand
    - name: Bepaal de laptopgroep
      # ansible.builtin.command: cat /etc/ansible/laptop-group
      ansible.builtin.shell: cat /usr/share/ansible/laptop-group 2>/dev/null
      register: group_file_content
      changed_when: false
      failed_when: false # Faal niet als het bestand niet bestaat

    # 2. Sla de inhoud op in een variabele (e.g., "leerlingen")
    - name: Zet de 'laptop_group' variabele
      ansible.builtin.set_fact:
        laptop_group: "{{ group_file_content.stdout | trim | default('geen_groep') }}"

  tasks:
    # 3. Importeer ALTIJD de 'common' taken
    - name: Voer common taken uit
      ansible.builtin.include_tasks: playbooks/common.yml

    # 4. Importeer de specifieke taken op basis van de variabele
    - name: Voer leerlingen taken uit
      ansible.builtin.include_tasks: playbooks/lln.yml
      when: laptop_group == 'leerlingen'

    - name: Voer leerkrachten taken uit
      ansible.builtin.include_tasks: playbooks/lkn.yml
      when: laptop_group == 'leerkrachten'

    - name: Voer administratie taken uit
      ansible.builtin.include_tasks: playbooks/admin.yml
      when: laptop_group == 'administratie'